language: python

services:
 - redis-server

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - "pip install httmock"
  - "pip install freezegun"
  - "pip install coveralls"
  - "pip install ."
  - "python setup.py install"
# command to run tests
script:
  nosetests --with-coverage --cover-package=snowplow_tracker
after_success:
  coveralls
