language: python

services:
 - redis-server

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - "pip install -r requirements-test.txt"
  - "pip install -e ."
# command to run tests
script:
  pytest --cov=snowplow_tracker
after_success:
  coveralls
